environment:
  matrix:
  - COMPILER: MSVC_16
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  verbosity: detailed
  parallel: true

cache:
  - c:\tools\vcpkg\installed\

install:
  - cd c:\projects\zeloengine
  - cd ThirdParty
  - md TEMP
  - git clone https://gitee.com/zolozy/imgui.git --branch docking TEMP\ImGui
  - xcopy /y/e ImGui TEMP\ImGui
  - xcopy /y/e/q TEMP\ImGui ImGui
  - git clone https://gitee.com/zolozy/optick.git TEMP\Optick
  - xcopy /y/e Optick TEMP\Optick
  - xcopy /y/e/q TEMP\Optick Optick
  -
  - cd c:\tools\vcpkg
  - git pull -q
  - .\bootstrap-vcpkg.bat -disableMetrics
  - vcpkg.exe integrate install
  - vcpkg.exe install --triplet x86-windows sdl2 glad assimp stb spdlog glm
  - vcpkg.exe install --triplet x86-windows sqlite3 curl glfw3 rapidjson gli
  - mklink /D /J c:\projects\zeloengine\ThirdParty\Vcpkg c:\tools\vcpkg\
  - c:\projects\zeloengine\ThirdParty\Vcpkg\vcpkg.exe --version

before_build:
  - cd c:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64

build_script:
  - echo "hello"
#  - mkdir build_vs2019
#  - cd build_vs2019
#  - cmake -DCMAKE_GENERATOR_PLATFORM=win32 -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G  "Visual Studio 16" ..
#  - cmake --build . --config debug -j 18
